# Large dataset streaming test - demonstrates memory efficiency
# This configuration generates a larger dataset to show immediate streaming

# AMQP connection and streaming configuration
amqp:
  url: "localhost:5672"
  queue: "data-gen-large-queue"
  username: "guest"
  password: "guest"

streaming:
  batch_size: 1000  # Larger batch size for efficiency
  include_metadata: true
  include_batch_info: true

# Data generation configuration
metadata:
  name: "Large Dataset Streaming Test"
  description: "Test configuration for large dataset streaming with memory efficiency"
  version: "1.0"

num_of_rows: 10000  # 10K rows split into 10 batches of 1K each
shuffle: false
write_output: false  # Disable file output for streaming

column_name:
  - id
  - user_id
  - transaction_id
  - amount
  - category
  - timestamp
  - status

file_writer: []  # No file writers for streaming

configs:
  - names: ["id"]
    strategy:
      name: "SERIES_STRATEGY"
      params:
        start: 1
        step: 1

  - names: ["user_id"]
    strategy:
      name: "RANDOM_NUMBER_RANGE_STRATEGY"
      params:
        start: 1000
        end: 9999

  - names: ["transaction_id"]
    strategy:
      name: "SERIES_STRATEGY"
      params:
        start: 100000
        step: 1

  - names: ["amount"]
    strategy:
      name: "RANDOM_NUMBER_RANGE_STRATEGY"
      params:
        start: 10
        end: 5000

  - names: ["category"]
    strategy:
      name: "DISTRIBUTED_CHOICE_STRATEGY"
      params:
        choices:
          Food: 25
          Transportation: 15
          Entertainment: 20
          Shopping: 20
          Bills: 10
          Healthcare: 10

  - names: ["timestamp"]
    strategy:
      name: "RANDOM_NUMBER_RANGE_STRATEGY"
      params:
        start: 1640995200
        end: 1672531199

  - names: ["status"]
    strategy:
      name: "DISTRIBUTED_CHOICE_STRATEGY"
      params:
        choices:
          completed: 80
          pending: 15
          failed: 5 