# Complete streaming configuration with masking functionality
# This file contains both data generation config with masking and AMQP streaming settings

# AMQP connection and streaming configuration
amqp:
  url: "localhost:5672"
  queue: "data-gen-masking-queue"
  username: "guest"
  password: "guest"

streaming:
  batch_size: 40
  include_metadata: true
  include_batch_info: true

# Data generation configuration with masking
metadata:
  name: "Masking and Streaming Test"
  description: "Test configuration combining masking functionality with streaming batches"
  version: "1.0"

num_of_rows: 200
shuffle: false
write_output: false  # Disable file output for streaming

column_name:
  - id
  - name
  - department
  - level
  - salary
  - bonus

file_writer: []  # No file writers for streaming

configs:
  - names: ["id"]
    strategy:
      name: "SERIES_STRATEGY"
      params:
        start: 1
        step: 1

  - names: ["name"]
    strategy:
      name: "RANDOM_NAME_STRATEGY"
      params: {}

  - names: ["department"]
    strategy:
      name: "DISTRIBUTED_CHOICE_STRATEGY"
      params:
        choices:
          Engineering: 40
          HR: 20
          Sales: 25
          Marketing: 15

  - names: ["level"]
    strategy:
      name: "DISTRIBUTED_CHOICE_STRATEGY"
      params:
        choices:
          Junior: 40
          Senior: 35
          Lead: 20
          Director: 5

  # Salary only for Engineering and HR employees
  - names: ["salary"]
    strategy:
      name: "RANDOM_NUMBER_RANGE_STRATEGY"
      params:
        start: 60000
        end: 120000
    mask: "department == 'Engineering' or department == 'HR'"

  # Bonus only for Senior and Lead level employees
  - names: ["bonus"]
    strategy:
      name: "RANDOM_NUMBER_RANGE_STRATEGY"
      params:
        start: 5000
        end: 15000
    mask: "level == 'Senior' or level == 'Lead'" 