# Complete streaming configuration for AMQP queue integration
# This file contains both data generation config and AMQP streaming settings

# AMQP connection and streaming configuration
amqp:
  # Use full AMQP URL for clarity when running from host
  url: "amqp://artemis:artemis@localhost:5672"
  queue: "data-gen-queue"
  # Optional idle delay (in seconds) between sending batches/messages
  delay_seconds: 0.5

streaming:
  batch_size: 100
  include_metadata: true
  include_batch_info: true

# Data generation configuration
metadata:
  name: "AMQP Streaming Test"
  description: "Simple configuration for testing AMQP messaging with streaming batches"
  version: "1.0"

num_of_rows: 35_000_000
shuffle: false
write_output: false  # Disable file output for streaming

column_name:
  - id
  - name
  - department
  - salary

file_writer: []  # No file writers for streaming

configs:
  - names: ["id"]
    strategy:
      name: "SERIES_STRATEGY"
      params:
        start: 1
        step: 1

  - names: ["name"]
    strategy:
      name: "RANDOM_NAME_STRATEGY"
      params: {}

  - names: ["department"]
    strategy:
      name: "DISTRIBUTED_CHOICE_STRATEGY"
      params:
        choices:
          Engineering: 40
          HR: 15
          Marketing: 20
          Sales: 25

  - names: ["salary"]
    strategy:
      name: "RANDOM_NUMBER_RANGE_STRATEGY"
      params:
        start: 50000
        end: 120000
