csv: utils/writers/file_writers/csv_writer.py
excel: utils/writers/file_writers/excel_writer.py
json: utils/writers/file_writers/json_writer.py
parquet: utils/writers/file_writers/parquet_writer.py
sqlite: utils/writers/file_writers/sqlite_writer.py
html: utils/writers/file_writers/html_writer.py
feather: utils/writers/file_writers/feather_writer.py 