name: Deploy to GitHub Pages

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

# Add permissions for GitHub token
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Build
      run: |
        cd frontend
        npm run build:gh-pages
      env:
        NODE_ENV: production
        VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL || 'https://your-backend-url.com' }}
        
    - name: Setup Pages
      if: github.ref == 'refs/heads/deploy'
      uses: actions/configure-pages@v5
      
    - name: Upload artifact
      if: github.ref == 'refs/heads/deploy'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./frontend/dist
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/deploy'
      id: deployment
      uses: actions/deploy-pages@v4 